compile:
	g++ -std=c++11 -Wall bucket_sort.cpp -o bucket_sort.out -fopenmp

run:
	./bucket_sort.out 10000

basic_compile:
	g++ -std=c++11 -Wall bucket_sort_basic.cpp -o bucket_sort_basic.out -fopenmp

basic_run:
	./run_basic.sh

x_clean:
	rm *.out